name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: npm install
        run: npm install
      
      # - name: lint
      #   run: npm run eslint
      
      - name: build
        run: npm run build
      
      # - name: test
      #   run: npm run test

      - name: create env file
        run: |
          touch .env
          echo SECRET=${{ secrets.SECRET }} >> .env
          echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env
          cat .env
      
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm start
          wait-on: http://localhost:3003
      
      # https://github.com/AkhileshNS/heroku-deploy/issues/84
      # - name: deploy
      #   if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
      #   uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: "lost-ark-tools" #Must be unique in Heroku
      #     heroku_email: ${{ secrets.HEROKU_EMAIL }}
          # healthcheck: "https://lost-ark-tools.herokuapp.com/health"
          # checkstring: "ok"
          # rollbackonhealthcheckfailed: true
      
      - uses: actions/checkout@v2 # quick fix for tag error
      - name: Bump version and push tag # merge to master
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598 #v1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      # - name: deployment pipeline success
      #   if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') && success() }}
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

      # - name: deployment pipeline failed
      #   if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') && failure() }}
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required